// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMfp7qPHveTftvKYFIaJDB48JPaalYhWA',
    appId: '1:1031899319245:web:4b385c1645f365824d5284',
    messagingSenderId: '1031899319245',
    projectId: 'my-mood-app-578b9',
    authDomain: 'my-mood-app-578b9.firebaseapp.com',
    storageBucket: 'my-mood-app-578b9.appspot.com',
    measurementId: 'G-FTE3TB1NPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoulSf00VQiTxomOQeVI9ggOqpv0-JecI',
    appId: '1:1031899319245:android:3e80052ce6aaa2504d5284',
    messagingSenderId: '1031899319245',
    projectId: 'my-mood-app-578b9',
    storageBucket: 'my-mood-app-578b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQn7MZfEKbmfGeEKer-CQoyiUq4LIerb0',
    appId: '1:1031899319245:ios:675ac32c47b6a7d54d5284',
    messagingSenderId: '1031899319245',
    projectId: 'my-mood-app-578b9',
    storageBucket: 'my-mood-app-578b9.appspot.com',
    iosBundleId: 'com.example.myMoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQn7MZfEKbmfGeEKer-CQoyiUq4LIerb0',
    appId: '1:1031899319245:ios:675ac32c47b6a7d54d5284',
    messagingSenderId: '1031899319245',
    projectId: 'my-mood-app-578b9',
    storageBucket: 'my-mood-app-578b9.appspot.com',
    iosBundleId: 'com.example.myMoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMfp7qPHveTftvKYFIaJDB48JPaalYhWA',
    appId: '1:1031899319245:web:ec4935ce97f7b13d4d5284',
    messagingSenderId: '1031899319245',
    projectId: 'my-mood-app-578b9',
    authDomain: 'my-mood-app-578b9.firebaseapp.com',
    storageBucket: 'my-mood-app-578b9.appspot.com',
    measurementId: 'G-YCNFZ7WDV1',
  );
}
